#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo "================================="
echo " Bharat Linux Boot Stage "
echo "================================="

mkdir -p /newroot

mount -t ext4 -o rw /dev/sda1 /newroot

exec switch_root /newroot /init
