#!/bin/sh

PIDFILE=/run/services/logd.pid

case "$1" in

start)

    if [ -f $PIDFILE ]; then
        echo "logd already running"
        exit 1
    fi

    /usr/bin/bharat-logd &

    echo $! > $PIDFILE

    echo "logd started"
    ;;

stop)

    if [ ! -f $PIDFILE ]; then
        echo "logd not running"
        exit 1
    fi

    kill $(cat $PIDFILE)

    rm -f $PIDFILE

    echo "logd stopped"
    ;;

status)

    if [ -f $PIDFILE ]; then
        echo "logd running PID $(cat $PIDFILE)"
    else
        echo "logd stopped"
    fi
    ;;

restart)

    $0 stop
    $0 start
    ;;

*)
    echo "Usage: logd {start|stop|status|restart}"
    ;;
esac
