#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

hostname Bharat-linux

echo ""
echo "========================================"
echo "Bharat-linux 0.1"
echo "By Bicky Prasad Yadav"
echo "Custom Linux distribution engineered from scratch."
echo "========================================"
echo ""
