#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys

echo ""
echo "========================================"
echo " Bharat-linux 0.1 "
echo "========================================"
echo ""
