#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

hostname Bharat-linux

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

ifconfig lo 127.0.0.1 up
ifconfig eth0 up
udhcpc -i eth0
echo ""
echo "================================="
echo " Bharat-linux system initialized "
echo "================================="
echo ""

echo "Kernel:"
uname -r

echo ""
echo "Memory:"
free

echo ""
cat /etc/motd
