#!/bin/busybox sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo ""
echo "================================="
echo " Bharat-linux booted successfully "
echo "================================="
echo ""

exec sh
