#!/bin/sh

USER=$1

if [ -z "$USER" ]; then
    echo "Usage: userdel <username>"
    exit 1
fi

if [ "$USER" = "root" ]; then
    echo "Cannot delete root"
    exit 1
fi

sed -i "/^$USER:/d" /etc/passwd
sed -i "/^$USER:/d" /etc/shadow
sed -i "/^$USER:/d" /etc/group

rm -rf /home/$USER

echo "User $USER deleted"
